In [2]:
import torch
torch.__version__

'1.12.1'

# 基本使用方法
创建一个矩阵

In [3]:
x = torch.empty(5,3)
x

tensor([[ 1.0562e+27,  4.5813e-41,  6.3797e+13],
        [-4.1716e+02,  2.2981e+25,  4.5813e-41],
        [ 1.0562e+27,  4.5813e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
x = torch.rand(5,3)
x

tensor([[0.3268, 0.1890, 0.6235],
        [0.1785, 0.5696, 0.7661],
        [0.3095, 0.4786, 0.4230],
        [0.3117, 0.6815, 0.5586],
        [0.6858, 0.5448, 0.5044]])

初始化一个全零的矩阵

In [5]:
x = torch.zeros(5,4, dtype = torch.long)
x

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

直接传入数据

In [6]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [8]:
x = x.new_ones(5,3, dtype = torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.randn_like(x, dtype = torch.float)
x

tensor([[-1.2016,  2.1770, -1.6481],
        [ 2.3362,  0.5231,  0.6626],
        [-0.6784, -0.9417, -0.4030],
        [-1.1060, -1.0681, -0.2780],
        [-3.2690, -0.5869, -0.6283]])

展示矩阵大小

In [10]:
x.size()

torch.Size([5, 3])

# 基本计算方法

In [11]:
y = torch.rand(5,3)
x + y

tensor([[-0.9437,  2.8478, -0.7954],
        [ 3.0577,  0.8049,  1.2711],
        [-0.5917, -0.0357, -0.1497],
        [-1.0915, -0.6201,  0.1979],
        [-2.7940,  0.2120, -0.4428]])

In [12]:
torch.add(x,y)

tensor([[-0.9437,  2.8478, -0.7954],
        [ 3.0577,  0.8049,  1.2711],
        [-0.5917, -0.0357, -0.1497],
        [-1.0915, -0.6201,  0.1979],
        [-2.7940,  0.2120, -0.4428]])

# 索引

In [13]:
x

tensor([[-1.2016,  2.1770, -1.6481],
        [ 2.3362,  0.5231,  0.6626],
        [-0.6784, -0.9417, -0.4030],
        [-1.1060, -1.0681, -0.2780],
        [-3.2690, -0.5869, -0.6283]])

In [14]:
x[:,1]

tensor([ 2.1770,  0.5231, -0.9417, -1.0681, -0.5869])

# view操作可以改变矩阵的维度

In [17]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# 与Numpy的协同操作

torch to numpy

In [18]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

numpy to torch

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)