# Tensor常见的形式有哪些
scalar
vector
matrix
n-dimensional tensor

In [1]:
import torch
from torch import tensor

# Scalar

In [2]:
x = tensor(42.)
x

tensor(42.)

In [3]:
x.dim()

0

In [4]:
2 * x

tensor(84.)

In [5]:
x.item()

42.0

# Vector
例如: [-5.,2.,0.], 在深度学习中通常指特征，例如词向量特征，某一维度特征等 v =[$v_{1}$,$v_{2}$,...$v_{n}$]

In [6]:
v = tensor([1.5,-0.5,3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [7]:
v.dim()

1

In [8]:
v.size()

torch.Size([3])

# Matrix
一般的计算都是矩阵，通常是多维的

In [10]:
M = tensor([[1.,2.],[3.,4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [11]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [12]:
tensor([1.,0.]).matmul(M)

tensor([1., 2.])

In [13]:
M*M

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [14]:
tensor([1.,2.]).matmul(M)

tensor([ 7., 10.])